db:
  adapter: postgresql
  host: localhost
  user: postgres
  password: postgres
pagination:
  page_size: 10
app:
  secret: secret
  name: geocoder
rabbitmq:
  consumer_pool: 10
logger:
  path: log/app.log
  level: info
